CC = gcc
CFLAGS = -Wall -Wextra -O2 -Ihal -Iapp -Icore -Ideps/data -Ideps/sort \
-Ideps/env -Ideps/mem -Ideps/log -Ideps/ext -Iplatform/linux/input \
-Iplatform/linux/video -Iplatform/linux/fs

TARGET = dcode

SRCS = platform/linux/input/input.c \
	platform/linux/video/video.c \
	platform/linux/fs/fs.c \
    deps/data/data.c \
	deps/sort/sort.c \
	deps/env/env.c \
	deps/mem/mem.c \
	deps/log/log.c \
	core/vismem/vismem.c \
	core/test/test.c \
	core/files/files.c \
	core/editor/editor.c \
	core/config/config.c \
	core/draw/draw.c \
	app/main.c

OBJS = $(SRCS:.c=.o)
OBJS := $(OBJS:.c=.o)

all: $(TARGET) clean

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) -x c -c $< -o $@

clean:
	@cp ./$(TARGET) ./bin/ 
	@rm ./$(TARGET) 
	@rm -f $(OBJS) $(TARGET)

.PHONY: all clean
