#ifndef APP_MAIN_H
#define APP_MAIN_H

// DEPS
#include "..\DEPS\DATA\DATA.H"
#include "..\DEPS\ENV\ENV.H"
#include "..\DEPS\INPUT\INPUT.H"
#include "..\DEPS\LOG\LOG.H"
#include "..\DEPS\MEM\MEM.H"
#include "..\DEPS\SORT\SORT.H"
#include "..\DEPS\VGA\VGAREGS.H"
#include "..\DEPS\EXT\VSNPRNTF.H"

// ENGINE
#include "..\ENG\DRAW.H"
#include "..\ENG\EDITOR.H"
#include "..\ENG\FILES.H"
#include "..\ENG\STD.H"
#include "..\ENG\TEST.H"
#include "..\ENG\VIDEO.H"
#include "..\ENG\VISMEM.H"
#include "..\ENG\CONFIG.H"
#include "..\ENG\FS.H"

#endif








